### ISSUE TITLE
Node-ffi doesn't have any Pointer object anymore

### ISSUE THREAD

**Issue by xionluhnis** [NaturalNode/node-lapack#1]
Hi,

I'm trying to install node-lapack to be used with sylvester, but it appears that the current version doesn't work with the last node-ffi.

The main trouble I encounter when running the example from README.md is that in lapack.js, you create new FFI.Pointer instances which do not exist in the current node-ffi. Is there something to rewrite because node-ffi was updated? How to change it so that it works with the current node-ffi version?

Where is this FFI.Pointer function?

**Comment by addaleax** [comment]
@kkoch986 looks like you can close this one now, too

**Comment by kkoch986** [comment]
yes thanks!
