### ISSUE TITLE
Published package still depends on deprecated `node-ffi`

### ISSUE THREAD

**Issue by jordanstephens** [NaturalNode/node-lapack#5]
The package I'm getting from npm is throwing this warning

    npm WARN deprecated node-ffi@0.5.7: Use the 'ffi' package instead. See https://github.com/rbranson/node-ffi/wiki/API-changes-from-v0.x-to-v1.x

It looks like the dependency has been updated with #4, but an updated package was never published to npm. Can you publish a new version to npm, please?

**Comment by kkoch986** [comment]
hey sorry about that, just pushed a new version to npm, thanks for pointing that out!
